-- CreateTable
CREATE TABLE "LedStrip" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT,
    "matrixCount" INTEGER NOT NULL DEFAULT 256,
    "ledCount" INTEGER NOT NULL DEFAULT 128,
    "matrixPin" INTEGER NOT NULL DEFAULT 13,
    "ledPin" INTEGER NOT NULL DEFAULT 12,
    "ledFreq" BIGINT NOT NULL DEFAULT 800000,
    "ledDma" INTEGER NOT NULL DEFAULT 10,
    "ledBrightness" INTEGER NOT NULL DEFAULT 90,
    "matrixBrightness" INTEGER NOT NULL DEFAULT 32,
    "ledInvert" BOOLEAN NOT NULL DEFAULT false,
    "ledChannel" INTEGER NOT NULL DEFAULT 0,
    "matrixChannel" INTEGER NOT NULL DEFAULT 1,
    "stripType" TEXT NOT NULL DEFAULT 'ws.W2811_STRIP_RGB'
);

-- CreateTable
CREATE TABLE "LedPattern" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "args" TEXT,
    "code" TEXT NOT NULL,
    "ledStripId" INTEGER,
    CONSTRAINT "LedPattern_ledStripId_fkey" FOREIGN KEY ("ledStripId") REFERENCES "LedStrip" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
